/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PopclipPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// settings.ts
var DEFAULT_SETTINGS = {
  mySetting: "default",
  actionHeading: "popclip",
  action: "advanced-uri"
};
var CUSTOM_SETTINGS = {
  useFrontmatter: true,
  usePopclipHeading: true,
  useHeader: true,
  useDatetimeAsFileName: true,
  useTable: true
};
var SETTINGS = {
  ...DEFAULT_SETTINGS,
  ...CUSTOM_SETTINGS
};

// src/modules/file-writer.ts
var import_obsidian = require("obsidian");

// src/utils/slugify.ts
function slugify(str) {
  str = str.replace(/^\s+|\s+$/g, "");
  str = str.toLowerCase();
  var from = "\u0131\xFC\xF6\xE7\u011F\xE0\xE1\xE4\xE2\xE8\xE9\xEB\xEA\xEC\xED\xEF\xEE\xF2\xF3\xF6\xF4\xF9\xFA\xFC\xFB\xF1\xE7\xB7/_,:;";
  var to = "iuocgaaaaeeeeiiiioooouuuunc------";
  for (var i = 0, l = from.length; i < l; i++) {
    str = str.replace(new RegExp(from.charAt(i), "g"), to.charAt(i));
  }
  str = str.replace(/[^a-z0-9 -]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-");
  if (str.startsWith("-")) {
    str = str.substring(1);
  } else if (str.endsWith("-")) {
    str = str.substring(0, str.length - 1);
  }
  return str;
}

// src/modules/file-writer.ts
var FileWriter = class {
  constructor(app, plugin) {
    this.app = app;
    this.plugin = plugin;
  }
  async writeToFile(payload) {
    const path = this.normalizePath(payload);
    this.app.vault.adapter.write(
      (0, import_obsidian.normalizePath)(path),
      this.setContent(payload)
    );
  }
  normalizePath(payload) {
    let fileName = this.normalizedDate();
    if (!this.plugin.settings.useDatetimeAsFileName) {
      fileName = payload.title ? payload.title.slice(0, 20).trim() : slugify(payload.clipping.slice(0, 20).trim());
    } else {
      fileName = this.normalizedDate();
    }
    fileName = fileName + ".md";
    let filePath = decodeURIComponent(payload.path);
    const path = (0, import_obsidian.normalizePath)(filePath + "/" + fileName);
    return path;
  }
  normalizedDate() {
    const datetime = new Date().toISOString().split(".")[0];
    return datetime.replaceAll("-", "").replaceAll(":", "").replace("T", "");
  }
  setFrontmatter(payload) {
    const elements = [
      "---",
      `title: "${payload == null ? void 0 : payload.title}"`,
      `source: ${(payload == null ? void 0 : payload.source) || ""}`,
      `date: ${new Date().toISOString()}`,
      "---"
    ];
    return elements.join("\n");
  }
  setHeader(payload) {
    return `# ${payload == null ? void 0 : payload.title}
`;
  }
  setTable(payload) {
    const currentDate = new Date().toISOString();
    const source = (payload == null ? void 0 : payload.source) || "";
  }
  setContent(payload) {
    const elements = [];
    if (this.plugin.settings.useFrontmatter) {
      elements.push(this.setFrontmatter(payload));
    }
    if (this.plugin.settings.useHeader && (payload == null ? void 0 : payload.title)) {
      elements.push(this.setHeader(payload));
    }
    elements.push((payload == null ? void 0 : payload.clipping) || "");
    return elements.join("\n");
  }
};

// src/modules/settings-tab.ts
var import_obsidian2 = require("obsidian");
var PopclipSettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    let { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Frontmatter").setDesc("Add frontmatter to the top of the file").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.useFrontmatter).onChange(async (value) => {
        this.plugin.settings.useFrontmatter = value;
        console.log("useFrontmatter", value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Header").setDesc(
      "Use the title of the source page if exists as header of note."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.useHeader).onChange(async (value) => {
        this.plugin.settings.useHeader = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Popclip Heading").setDesc(
      "IMPORTANT!!! Deactivate this if you got error when using popclip with this plugin. This settings can broke things. Thus, always take a backup before changing this setting."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.usePopclipHeading).onChange(async (value) => {
        console.log("setting usePopclipHeading", value);
        this.plugin.settings.usePopclipHeading = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

// main.ts
var PopclipPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new PopclipSettingsTab(this.app, this));
    this.registerObsidianProtocolHandler(SETTINGS.action, async (ev) => {
      if (ev == null ? void 0 : ev.heading) {
        if ((ev == null ? void 0 : ev.heading) === SETTINGS.actionHeading) {
          new FileWriter(this.app, this).writeToFile(JSON.parse(ev.data));
        }
      } else if (!this.settings.usePopclipHeading) {
        new FileWriter(this.app, this).writeToFile(JSON.parse(ev.data));
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
  }
};
